FROM alpine:edge

ENV JAVA_HOME=/usr/lib/jvm/java-1.8-openjdk

RUN apk add --no-cache bash bats curl docker git maven openjdk8

RUN echo '<settings><localRepository>/maven-cache/repository</localRepository></settings>' \
  > /settings.xml

VOLUME ["/maven-cache"]
