FROM alpine:3.6

# Install Some tools
RUN apk add --no-cache \
  bash \
  bats \
  docker \
  git \
  maven \
  openjdk8

ENV JAVA_HOME=/usr/lib/jvm/java-1.8-openjdk \
  MAVEN_HOME=/usr/share/java/maven-3

RUN mkdir -p /root/.m2/ \
  && echo '<settings><localRepository>/maven-cache/repository</localRepository></settings>' \
  > "/root/.m2/settings.xml"

VOLUME ["/maven-cache"]
