FROM alpine:edge

# Install Some tools
RUN apk add --no-cache \
  docker \
  git

RUN echo '<settings><localRepository>/maven-cache/repository</localRepository></settings>' \
  > "${MAVEN_HOME}/settings.xml"

VOLUME ["/maven-cache"]
